Laba_2/Models/DatabaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Laba_2.Models
{
    public class Person
    {
        [HiddenInput(DisplayValue = false)]
        public int PersonId { get; set; }

        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Display(Name = "Возраст")]
        public uint PersonAge { get; set; }

        [Display(Name = "Телефон")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Display(Name = "Наличие премиум подписки")]
        public bool PremiumSub { get; set; }
    }
}

Laba_2/Controllers/DatabaseController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Laba_2.Models;
using System.Web;
using System.Reflection;


namespace Laba_2.Controllers
{
    public class DatabaseController : Controller
    {
        // Список экземпляров Person
        private static List<Person> _personsList = new List<Person>();

        // Создание аккаунта
        // GET: /Database/Creat_Data
        [HttpGet]
        public ActionResult Creat_Data()
        {
            if (Session["user"] == null)
            {
                Session["user"] = 0;
            }
            else
            {
                Session["user"] = Int32.Parse(Convert.ToString(Session["user"])) + 1;
            }
            return View("Creat_Data");
        }

        // Просмотр созданного аккаунта 
        [HttpPost]
        public ActionResult View_Data(Person person)
        {
            person.PersonId = Int32.Parse(Convert.ToString(Session["user"]));
            _personsList.Add(person);
            return View("View_Data", person);
        }

        // Просмотр базы данных
        public ActionResult Data_Base()
        {
            // true - внешний метод, false - внутренний;
            TempData["method"] = false; 
            return View("Data_Base", _personsList);
        }
    }
}

Laba_2/Views/Database/Creat_Data.cshtml
@model Laba_2.Models.Person

@{
    Layout = "~/Views/__BasicLayout.cshtml";
    ViewBag.Title = "CreatePerson";
}

<style>
    h2 {
        font-size: 28px;
        margin-bottom: 20px;
        text-transform: uppercase;
        text-align: center;
    }

    form {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    label {
        text-align:left;
        font-size: 18px;
        width: 30%;
        font-weight: bold;
        margin-bottom: 10px;
        text-transform: uppercase;
    }

    .check-box{
        width: 20px;
    }
    
    input {
        padding: 10px;
        font-size: 16px;
        border-radius: 5px;
        border: 1px solid #ccc;
        margin-bottom: 20px;
        width: 30%;
        box-sizing: border-box;
    }

    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: all 0.3s ease-in-out;
        margin-top: 20px;
        width: 20%;
    }

    button:hover {
        background-color: #3e8e41;
    }
</style>

<h2>Создание аккаунта:</h2>
@using (Html.BeginForm("View_Data", "Database", FormMethod.Post))
{
    <label>@Html.LabelFor(m => m.FirstName)</label>
    @Html.EditorFor(m => m.FirstName)

    <label>@Html.LabelFor(m => m.LastName)</label>
    @Html.EditorFor(m => m.LastName)

    <label>@Html.LabelFor(m => m.PersonAge)</label>
    @Html.EditorFor(m => m.PersonAge)

    <label>@Html.LabelFor(m => m.Phone)</label>
    @Html.EditorFor(m => m.Phone)

    <label>@Html.LabelFor(m => m.Email)</label>
    @Html.EditorFor(m => m.Email)

    <label>@Html.LabelFor(m => m.Password)</label>
    @Html.EditorFor(m => m.Password)

    <div>@Html.LabelFor(m => m.PremiumSub)
    @Html.EditorFor(m => m.PremiumSub)</div>

    <button type="submit">Создать</button>
}

Laba_2/Views/Database/Data_Base.cshtml
@model List<Laba_2.Models.Person>
@using Laba_2.external_method

@{
    Layout = "~/Views/__BasicLayout.cshtml";
    ViewBag.Title = "Data Base";
}

<style>
    h2 {
        font-size: 36px;
        color: #333;
        text-align: center;
        margin-top: 20px;
    }

    /* Стилизация таблицы */
    .table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

    .hyperlink {
        font-size: 18px;
        text-align: center;
        margin-top: 20px;
    }

        .hyperlink a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border-radius: 5px;
            text-decoration: none;
            transition: all 0.3s ease-in-out;
        }

            .hyperlink a:hover {
                background-color: #3e8e41;
            }
</style>


@helper ListArrayItems(List<Laba_2.Models.Person> Model)
{
    foreach (var person in Model)
    {
        <tr>
            <td>@person.PersonId</td>
            <td>@person.FirstName</td>
            <td>@person.LastName</td>
            <td>@person.PersonAge</td>
            <td>@person.Phone</td>
            <td>@person.Email</td>
            <td>@(person.PremiumSub ? "Yes" : "No")</td>
        </tr>
    }
}

<h2>Data Base</h2>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Phone</th>
            <th>Email</th>
            <th>Premium Subscription</th>
        </tr>
    </thead>
    <tbody>
        @if ((bool)TempData["method"])
        {
            @Html.ListArrayItems(Model)
        }
        else
        {
            @ListArrayItems(Model);
        }
    </tbody>
</table>
<p class="hyperlink">@Html.ActionLink("Создать аккаунт", "Creat_Data")</p>

Laba_2/Views/Database/View_Data.cshtml
@model Laba_2.Models.Person

@{
    Layout = "~/Views/__BasicLayout.cshtml";
    ViewBag.Title = "Созданный аккаунт";
}

<style>
    h2 {
        text-align: center;
        font-size: 28px;
        margin-bottom: 20px;
        text-transform: uppercase;
    }

    .account-info {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-bottom: 20px;
    }

        .account-info .display-label {
            text-align: left;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
            width: 30%;
            text-transform: uppercase;
        }

        .account-info .display-field {
            padding: 10px;
            font-size: 16px;
            border-radius: 5px;
            border: 1px solid #ccc;
            margin-bottom: 20px;
            width: 30%;
            box-sizing: border-box;
        }

    .hyperlink {
        font-size: 18px;
        text-align: center;
        margin-top: 20px;
    }

        .hyperlink a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border-radius: 5px;
            text-decoration: none;
            transition: all 0.3s ease-in-out;
        }

            .hyperlink a:hover {
                background-color: #3e8e41;
            }
</style>

<h2>Созданный аккаунт:</h2>

<div class="account-info">
    @Html.LabelForModel()
    @Html.DisplayForModel()
</div>

<p class="hyperlink">@Html.ActionLink("Перейти к созданию", "Creat_Data")</p>
<p class="hyperlink">@Html.ActionLink("База Данных", "Data_Base")</p>

Laba_2/Views/__BasicLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>